### ISSUE TITLE
Issues when releasing 1.4.12 / 1.4.13

### ISSUE THREAD

**Issue by mccartney** [scapegoat-scala/scapegoat#647]
It was a long time since I did the last release and I might have forgotten something.

I tried to release 1.4.12 by changing the (hidden) draft release and labeling it `1.4.2`, but the Github Action workflow has failed with:
```
2022-05-04 19:48:12.146Z error [Sonatype] 
java.io.IOException: Supplied file /home/runner/work/scapegoat/scapegoat/target/sonatype-staging/1.4.12+20-0d8e10c7-SNAPSHOT is a not an existing directory!
	at org.sonatype.spice.zapper.fs.AbstractDirectory.<init>(AbstractDirectory.java:32)
	at org.sonatype.spice.zapper.fs.DirectoryIOSource.<init>(DirectoryIOSource.java:68)
```

Not sure if this is some transient issue or some misconfiguration or what.

Will debug later.

**Comment by mccartney** [comment]
1. I think my mistake might have been not to create a git tag for this release.
2. Editing the release to create a tag didn't help.
3. So now trying to move the tag (by adding some commit first: https://github.com/scapegoat-scala/scapegoat/commit/6edbf94c18183301b1e86c7f558897fbc386ea6b)

**Comment by mccartney** [comment]
Ah. :facepalm: 1.4.12 was already released in January 2022, it's just Github Releases didn't know it.

**Comment by mccartney** [comment]
Trying 1.4.13 release now.

**Comment by mccartney** [comment]
OK. The workflow for 1.4.13 completed with success. Let's observe if a Maven artifact shows up soon.

**Comment by mccartney** [comment]
Looks like it worked, e.g.
https://repo1.maven.org/maven2/com/sksamuel/scapegoat/scalac-scapegoat-plugin_2.13.8/1.4.13/
